<div class="container mt-5">
    <h4 class="text-danger mb-3">You need to setup your homepage first!</h4>

    <p>1. Go to <strong>Admin</strong> -> <strong>Plugins</strong> then activate all plugins.</p>
    <p>2. Go to <strong>Admin</strong> -> <strong>Pages</strong> and create a page:</p>

    <div class="mt-2">
        <div class="mb-3">- Content:</div>
        <div>
            <code><pre class="border rounded p-3">[hero-banner title="Boost your project's speed and efficiency." subtitle="Free Lifetime Update" description="Access top-tier group mentoring plans and exclusive professional benefits for your team." primary_action_label="Explore Now" primary_action_url="#" primary_action_icon="ti ti-arrow-up-right" secondary_action_label="Contact Us" secondary_action_url="/contact" secondary_action_icon="ti ti-phone" bottom_image="backgrounds/hb-bottom.png" right_background_image="backgrounds/hb-right.png" shape_1_image="shapes/1.png" shape_2_image="shapes/2.png" shape_3_image="shapes/3.png" floating_card_image="shapes/4.png" floating_card_title="Book A Call" floating_card_description="Customer activity can be easily &lt;br&gt; tracked with one click" floating_card_button_label="Free Update"][/hero-banner]
[partners quantity="7" name_1="Framer" image_1="partners/1.png" url_1="https://google.com" open_in_new_tab_1="1" name_2="Reddit" image_2="partners/2.png" url_2="https://google.com" open_in_new_tab_2="1" name_3="Netflix" image_3="partners/3.png" url_3="https://google.com" open_in_new_tab_3="1" name_4="Microsoft" image_4="partners/4.png" url_4="https://google.com" open_in_new_tab_4="1" name_5="Discover" image_5="partners/5.png" url_5="https://google.com" open_in_new_tab_5="1" name_6="Lemon Squeezy" image_6="partners/6.png" url_6="https://google.com" open_in_new_tab_6="1" name_7="Paypal" image_7="partners/7.png" url_7="https://google.com" open_in_new_tab_7="1"][/partners]
[features style="1" title="Together, we are creating a &lt;span&gt;Bright Future&lt;/span&gt;" subtitle="Our Features" image="backgrounds/feature.png" quantity="4" title_1="Work organization" description_1="A business consultant provides expert advice and guidance to businesses on various aspects." icon_1="ti ti-briefcase" title_2="Strategy Development" description_2="Business consultants play a crucial role by offering expert advice and guidance to companies" icon_2="ti ti-bulb" title_3="Data analytics" description_3="Consultants provide invaluable expertise to businesses, assisting them with strategic advice" icon_3="ti ti-chart-bar" title_4="Business Intelligence" description_4="Through their deep understanding of industry trends and best practices, consultants empower organizations" icon_4="ti ti-chart-pie"][/features]
[features style="2" title="Scalable Business for &lt;span&gt;Startups&lt;/span&gt;" subtitle="Our Features" checklist="Success Accelerators\nStarted politician Club\nBusiness Intelligence\nData analytics" image="shapes/img-favicon.png" floating_card_image="backgrounds/feature-2.png" floating_card_title="Transform Your Business \n Into Profession" floating_card_description="Achieve Your a of Business" floating_card_button_label="Free Update" floating_card_button_url="#" quantity="2" title_1="Efficiency Experts" description_1="A business consultant provides expert advice and guidance to businesses on various aspects." icon_1="ti ti-briefcase" title_2="Strategic Solutions" description_2="Discover why hundreds of millions people use Infinia to chat and call every day." icon_2="ti ti-bulb"][/features]
[features style="3" title="Powerful agency for corporate business." subtitle="Company's vision" description="Provide your team with top-tier group mentoring programs and exceptional professional benefits." image="backgrounds/feature-3.png" primary_action_label="Get Free Quote" primary_action_url="/contact" primary_action_icon="ti ti-arrow-up-right" secondary_action_label="How We Work" secondary_action_url="/contact" floating_card_image="shapes/testimonial-star.png" floating_card_title="Rate For Us" floating_card_description="Loved by over 4k \n happy clients" quantity="2" title_1="99%" description_1="Genuine repeated happy customers." title_2="98%" description_2="Trusted by companies."][/features]
[services subtitle="What We Offers" title="Explore Our Services" description="By doing a financial analysis of these statements, you can see &lt;br&gt; whether you have enough working capital." service_ids="1,2,6,3,4,5" background_image="backgrounds/service.png"][/services]
[teams subtitle="Our Team Members" title="Meet Our Team" description="Meet the talented and passionate team members who drive our company forward every day." team_ids="1,2,3,4,5,6,7,8" background_image="backgrounds/team.png"][/teams]
[pricing-plans subtitle="Our Plans" title="Pricing Plans" description="⚡We’ve got a pricing plan that’s perfect for you" package_ids="1,2,3,4"][/pricing-plans]
[testimonials subtitle="Testimonials" title="What our clients say" description="Access top-tier group mentoring plans and exclusive professional benefits for your team. 🔥" testimonial_ids="1,2,3,4" background_image="backgrounds/testimonial.png" primary_action_label="Contact Us" primary_action_url="/contact" primary_action_icon="ti ti-phone" secondary_action_label="Help Center" secondary_action_url="/contact" secondary_action_icon="ti ti-arrow-right"][/testimonials]
[blog-posts subtitle="From Blog" title="Our Latest Articles" description="Explore the insights and trends shaping our industry" paginate="3" action_label="View All Articles" action_url="/blog"][/blog-posts]</pre></code>
        </div>
        <br>
        <div class="mb-3">- Template: <strong>Default</strong>.</div>
    </div>
    <p>3. Then go to <strong>Admin</strong> -> <strong>Appearance</strong> -> <strong>Theme options</strong> -> <strong>Page</strong> to set your homepage.</p>
</div>
